# golangci-lint configuration for KubeVirt Shepherd
# See: https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - dupl
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - goimports
    - gosec
    - misspell
    - nilerr
    - noctx
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment # too noisy
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: error-return
      - name: error-strings
      - name: increment-decrement
      - name: var-naming
      - name: unexported-return
  exhaustive:
    default-signifies-exhaustive: true
  goimports:
    local-prefixes: kv-shepherd.io/shepherd
  dupl:
    threshold: 150
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-rules:
    # Allow dot imports in test files for testify
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    # Allow naked goroutine in main.go server start (exempt)
    - path: cmd/server/main\.go
      text: "naked goroutine"
    # Allow naked goroutine in worker pool infrastructure
    - path: internal/pkg/worker/
      text: "naked goroutine"
  max-issues-per-linter: 50
  max-same-issues: 10
