# Vacuum ruleset for KubeVirt Shepherd (ADR-0029)
# Vacuum is Spectral-compatible: https://quobix.com/vacuum/rulesets/
# Extends the recommended OpenAPI ruleset with project-specific rules.
extends:
  - - "spectral:oas"
    - "recommended"

rules:
  # Require operation IDs on all endpoints
  operation-operationId: true

  # Require descriptions on operations
  operation-description: true

  # Require tags on operations
  operation-tags: true

  # Require info contact
  info-contact: true

  # Require info license
  info-license: true

  # No eval in markdown
  no-eval-in-markdown: true

  # No script tags in markdown
  no-script-tags-in-markdown: true
